version: '3.4'

services:  
  weatherbot:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Data Source=Database.db;
      - BotSettings__HookUrl=https://ebe4-95-28-187-78.eu.ngrok.io
    ports:
      - "4000:4000"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro      
    command: ["dotnet", "ef", "database update"]
  proxy:
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "80:80"